### PR TITLE
midna.kvconfig update

### PR DESCRIPTION
**Pull request by jomada**

### CODE REVIEW

**Comment by demmm** [comment]
Your fork is too far behind to be able to merge, which is the change to toggle the Octopi background?
EDIT:
NVM, found disabling lineedit interior works for Octopi toggle, not a solution.

**Comment by demmm** [comment]
Not a proper fix, can't be merged, too far behind, need to sync the fork with master before opening a PR.

**Comment by jomada** [comment]
Only changed the LineEdit Interior = false option I didn't find another way

**Comment by demmm** [comment]
>I didn't find another way

Same here, thus I opened an issue in Kvantum, which was closed right away....

**Pull request closed without merging**
